key:
  USUBJID
columns:
  STUDYID:
    ResearchStudy:
      identifier:
        value
  DOMAIN:
  USUBJID:
    ResearchSubject:
      identfier: 
        value
  LBSEQ:
  LBGRPID:
  LBREFID:
  LBSPID:
  LBTESTCD:
    Observation:
      code:
        _lookup_loinc_code
  LBTEST:
    Observation:
      code:
        _lookup_loinc_name
  LBCAT:
  LBSCAT:
  LBORRES:
    Observation:
      valueQuantity:
        value
  LBORRESU:
    Observation:
      valueQuantity:
        _lookup_unit_ucum
  LBORNRLO:
    Observation:
      referenceRange:
        low:
          value
  LBORNRHI:
    Observation:
      referenceRange:
        high:
          value
  LBSTRESC:
  LBSTRESN:
  LBSTRESU:
  LBSTNRLO:
  LBSTNRHI:
  LBSTNRC:
  LBNRIND:
  LBSTAT:
  LBREASND:
  LBNAM:
  LBLOINC:
    Observation:
      code:
        value
  LBSPEC:
  LBSPCCND:
  LBMETHOD:
  LBBLFL:
  LBFAST:
  LBDRVFL:
  LBTOX:
  LBTOXGR:
  VISITNUM:
  VISIT:
  VISITDY:
  LBDTC:
    Observation:
      
  LBENDTC:
  LBDY:
  LBTPT:
  LBTPTNUM:
  LBELTM:
  LBTPTREF:
  LBRFTDTC: