key:
  USUBJID
columns:
  STUDYID:
    ResearchStudy:
      identfier:
        value
  DOMAIN:
  USUBJID:
    ResearchSubject:
      identfier: 
        value
    Observation:
      subject:
        Patient
  VSSEQ:
  VSGRPID:
  VSSPID:
  VSTESTCD:
    Observation:
      code:
        _lookup_loinc_code
  VSTEST:
    Observation:
      code:
        _lookup_loinc_test
  VSCAT:
  VSSCAT:
  VSPOS:
    Observation:
      code:
        _lookup_loinc_position
  VSORRES:
    Observation:
      valueQuantity:
        value
  VSORRESU:
    Observation:
      valueQuantity:
        _lookup_unit_ucum
  VSSTRESC:
  VSSTRESN:
  VSSTRESU:
  VSSTAT:
  VSREASND:
  VSLOC:
    Observation:
      bodySite:
        _lookup_snomed_code
  VSLAT:
  VSBLFL:
  VSDRVFL:
  VISITNUM:
    Encounter:
      identifier:
        value
  VISIT:
    Observation:
      encounter
  VISITDY:
  VSDTC:
    Observation:
      effectiveDateTime
  VSDY:
  VSTPT:
  VSTPTNUM:
  VSELTM:
  VSTPTREF:
  VSRFTDTC:
